package org.pgjava.sql.ast;

public enum AlterTableType {
    ADD_COLUMN, DROP_COLUMN, ALTER_COLUMN_TYPE, SET_NOT_NULL, DROP_NOT_NULL,
    SET_DEFAULT, DROP_DEFAULT, ADD_CONSTRAINT, DROP_CONSTRAINT, VALIDATE_CONSTRAINT,
    RENAME_COLUMN, RENAME_TABLE, SET_OPTIONS, RESET_OPTIONS, OTHER
}
