package org.pgjava.jdbc;

import org.pgjava.engine.PgNotification;
import org.pgjava.engine.Session;

import java.sql.*;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

/** JDBC Connection backed by a pgjava {@link Session}. */
public final class PgJavaConnection implements Connection {

    private final Session session;
    private final String  url;
    private final String  userName;
    private boolean autoCommit  = true;
    private boolean readOnly    = false;
    private int     isolation   = TRANSACTION_READ_COMMITTED;
    private String  schema      = null;
    private SQLWarning warnings  = null;

    PgJavaConnection(Session session, String url) {
        this(session, url, "pgjava");
    }

    PgJavaConnection(Session session, String url, String userName) {
        this.session  = session;
        this.url      = url;
        this.userName = userName != null ? userName : "pgjava";
    }

    Session session() { return session; }

    String getMetaUrl() { return url; }

    String getUserNameValue() { return userName; }

    // -------------------------------------------------------------------------
    // Statement factory

    @Override
    public Statement createStatement() throws SQLException {
        checkOpen();
        return new PgJavaStatement(this);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
        return createStatement();
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return createStatement();
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        checkOpen();
        return new PgJavaPreparedStatement(this, sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public CallableStatement prepareCall(String sql) throws SQLException {
        checkOpen();
        return new PgJavaCallableStatement(this, sql);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return prepareCall(sql);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return prepareCall(sql);
    }

    // -------------------------------------------------------------------------
    // Transaction control

    @Override public boolean getAutoCommit() throws SQLException { checkOpen(); return autoCommit; }

    @Override
    public void setAutoCommit(boolean autoCommit) throws SQLException {
        checkOpen();
        if (this.autoCommit == autoCommit) return;
        if (autoCommit && !this.autoCommit) {
            // JDBC spec: switching from manual to auto-commit commits pending work
            session.execute("COMMIT");
        }
        this.autoCommit = autoCommit;
        if (!autoCommit) {
            // Starting explicit transaction
            session.execute("BEGIN");
        }
    }

    @Override
    public void commit() throws SQLException {
        checkOpen();
        session.execute("COMMIT");
    }

    @Override
    public void rollback() throws SQLException {
        checkOpen();
        session.execute("ROLLBACK");
    }

    @Override
    public void rollback(Savepoint savepoint) throws SQLException {
        checkOpen();
        if (savepoint instanceof PgJavaSavepoint sp) {
            session.execute("ROLLBACK TO SAVEPOINT " + sp.name());
        }
    }

    @Override
    public Savepoint setSavepoint() throws SQLException {
        return setSavepoint("sp_" + System.nanoTime());
    }

    @Override
    public Savepoint setSavepoint(String name) throws SQLException {
        checkOpen();
        session.execute("SAVEPOINT " + name);
        return new PgJavaSavepoint(name);
    }

    @Override
    public void releaseSavepoint(Savepoint savepoint) throws SQLException {
        checkOpen();
        if (savepoint instanceof PgJavaSavepoint sp) {
            session.execute("RELEASE SAVEPOINT " + sp.name());
        }
    }

    // -------------------------------------------------------------------------
    // Connection properties

    @Override public boolean isReadOnly()         throws SQLException { return readOnly; }
    @Override public void    setReadOnly(boolean v) throws SQLException { this.readOnly = v; }
    @Override public int     getTransactionIsolation() throws SQLException { return isolation; }
    @Override public void    setTransactionIsolation(int level) throws SQLException { this.isolation = level; }
    @Override public String  getCatalog()          throws SQLException { return session.database().name(); }
    @Override public void    setCatalog(String c)  throws SQLException {}
    @Override public String  getSchema()           throws SQLException { return schema; }
    @Override public void    setSchema(String s)   throws SQLException { this.schema = s; }

    @Override public SQLWarning getWarnings()      throws SQLException { return warnings; }
    @Override public void       clearWarnings()    throws SQLException { warnings = null; }

    @Override public String  nativeSQL(String sql) throws SQLException { return sql; }

    @Override public Map<String, Class<?>> getTypeMap() throws SQLException { return Map.of(); }
    @Override public void setTypeMap(Map<String, Class<?>> map) throws SQLException {}

    @Override public int  getHoldability() throws SQLException { return ResultSet.CLOSE_CURSORS_AT_COMMIT; }
    @Override public void setHoldability(int h) throws SQLException {}

    @Override public DatabaseMetaData getMetaData() throws SQLException {
        checkOpen();
        return new PgJavaDatabaseMetaData(this);
    }

    // -------------------------------------------------------------------------
    // isValid — used by HikariCP connection validation

    @Override
    public boolean isValid(int timeout) throws SQLException {
        if (isClosed()) return false;
        try {
            session.execute("SELECT 1");
            return true;
        } catch (UnsupportedOperationException e) {
            // Engine not yet implemented — connection is still alive
            return true;
        } catch (SQLException e) {
            return false;
        }
    }

    // -------------------------------------------------------------------------
    // Lifecycle

    @Override public void close() throws SQLException { session.close(); }
    @Override public boolean isClosed() throws SQLException { return session.isClosed(); }

    private void checkOpen() throws SQLException {
        if (session.isClosed()) throw new SQLException("Connection is closed");
    }

    // -------------------------------------------------------------------------
    // Client info (no-ops)

    @Override public void setClientInfo(String name, String value) throws SQLClientInfoException {}
    @Override public void setClientInfo(Properties props) throws SQLClientInfoException {}
    @Override public String getClientInfo(String name) throws SQLException { return null; }
    @Override public Properties getClientInfo() throws SQLException { return new Properties(); }

    // -------------------------------------------------------------------------
    // Unsupported JDBC 4+ features

    @Override public Clob   createClob()   throws SQLException { throw new SQLFeatureNotSupportedException("createClob"); }
    @Override public Blob   createBlob()   throws SQLException { throw new SQLFeatureNotSupportedException("createBlob"); }
    @Override public NClob  createNClob()  throws SQLException { throw new SQLFeatureNotSupportedException("createNClob"); }
    @Override public SQLXML createSQLXML() throws SQLException { throw new SQLFeatureNotSupportedException("createSQLXML"); }
    @Override public Array  createArrayOf(String typeName, Object[] elements) throws SQLException {
        return new PgJavaArray(typeName, PgJavaArray.sqlTypeForName(typeName), elements);
    }
    @Override public Struct createStruct(String typeName, Object[] attributes) throws SQLException { throw new SQLFeatureNotSupportedException("createStruct"); }

    @Override public void abort(Executor executor) throws SQLException { close(); }
    @Override public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException {}
    @Override public int  getNetworkTimeout() throws SQLException { return 0; }

    @Override public <T> T unwrap(Class<T> iface) throws SQLException {
        if (iface.isInstance(this)) return iface.cast(this);
        throw new SQLException("Not a wrapper for " + iface);
    }
    @Override public boolean isWrapperFor(Class<?> iface) { return iface.isInstance(this); }

    // -------------------------------------------------------------------------
    // LISTEN/NOTIFY

    /**
     * Drain all pending asynchronous notifications that have arrived on channels
     * this connection is currently listening to.
     *
     * <p>Mirrors {@code org.postgresql.PGConnection#getNotifications()}.
     *
     * @return array of pending notifications; empty (not null) if none.
     */
    public PgNotification[] getNotifications() throws SQLException {
        checkOpen();
        return session.drainNotifications();
    }

    // -------------------------------------------------------------------------
    // Inner savepoint

    private record PgJavaSavepoint(String name) implements Savepoint {
        @Override public int    getSavepointId()   throws SQLException { throw new SQLException("Named savepoint has no numeric id"); }
        @Override public String getSavepointName() throws SQLException { return name; }
    }
}
