package org.pgjava.jdbc;

import org.pgjava.engine.QueryResult;
import org.pgjava.engine.Session;

import java.sql.*;

/** Simple Statement implementation backed by a {@link Session}. */
class PgJavaStatement implements Statement {

    protected final PgJavaConnection conn;
    protected final Session session;

    private boolean   closed        = false;
    private ResultSet currentRS     = null;
    private ResultSet generatedKeys = null;
    private int       updateCount   = -1;
    private int       maxRows       = 0;
    private int       queryTimeout  = 0;
    private int       fetchSize     = 0;

    PgJavaStatement(PgJavaConnection conn) {
        this.conn    = conn;
        this.session = conn.session();
    }

    // -------------------------------------------------------------------------

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        checkOpen();
        QueryResult result = executeInternal(sql);
        if (!result.isQuery())
            throw new SQLException("Statement did not return a ResultSet");
        PgJavaResultSet rs = new PgJavaResultSet(result);
        rs.setStatement(this);
        currentRS   = rs;
        updateCount = -1;
        return currentRS;
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        checkOpen();
        QueryResult result = executeInternal(sql);
        generatedKeys = null;
        if (result.isQuery()) {
            // DML with RETURNING — store as generated keys; update count = row count
            PgJavaResultSet gk = new PgJavaResultSet(result);
            gk.setStatement(this);
            generatedKeys = gk;
            updateCount   = result.rows() != null ? result.rows().size() : 0;
        } else {
            updateCount = result.updateCount();
        }
        currentRS = null;
        return updateCount;
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        checkOpen();
        QueryResult result = executeInternal(sql);
        generatedKeys = null;
        if (result.isQuery()) {
            PgJavaResultSet rs = new PgJavaResultSet(result);
            rs.setStatement(this);
            currentRS   = rs;
            updateCount = -1;
            return true;
        } else {
            currentRS   = null;
            updateCount = result.updateCount();
            return false;
        }
    }

    protected QueryResult executeInternal(String sql) throws SQLException {
        try {
            return session.execute(sql);
        } catch (UnsupportedOperationException e) {
            throw e; // let harness catch it
        } catch (SQLException e) {
            throw e;
        }
    }

    // -------------------------------------------------------------------------

    @Override public ResultSet getResultSet()  throws SQLException { checkOpen(); return currentRS; }
    @Override public int getUpdateCount()      throws SQLException { checkOpen(); return updateCount; }
    @Override public boolean getMoreResults()  throws SQLException { checkOpen(); currentRS = null; updateCount = -1; return false; }

    @Override public int     getMaxRows()        throws SQLException { return maxRows; }
    @Override public void    setMaxRows(int max)  throws SQLException { this.maxRows = max; }
    @Override public int     getQueryTimeout()    throws SQLException { return queryTimeout; }
    @Override public void    setQueryTimeout(int seconds) throws SQLException { this.queryTimeout = seconds; }
    @Override public int     getFetchSize()       throws SQLException { return fetchSize; }
    @Override public void    setFetchSize(int rows) throws SQLException { this.fetchSize = rows; }
    @Override public int     getFetchDirection()  throws SQLException { return ResultSet.FETCH_FORWARD; }
    @Override public void    setFetchDirection(int d) throws SQLException {}
    @Override public int     getResultSetType()   throws SQLException { return ResultSet.TYPE_FORWARD_ONLY; }
    @Override public int     getResultSetConcurrency() throws SQLException { return ResultSet.CONCUR_READ_ONLY; }
    @Override public int     getResultSetHoldability() throws SQLException { return ResultSet.CLOSE_CURSORS_AT_COMMIT; }
    @Override public int     getMaxFieldSize()    throws SQLException { return 0; }
    @Override public void    setMaxFieldSize(int max) throws SQLException {}
    @Override public boolean getMoreResults(int current) throws SQLException { return false; }
    @Override public ResultSet getGeneratedKeys() throws SQLException {
        return generatedKeys != null ? generatedKeys : PgJavaResultSet.empty(java.util.List.of());
    }
    @Override public int     executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        // RETURN_GENERATED_KEYS: SQL may already contain RETURNING (pgjdbc appends it)
        return executeUpdate(sql);
    }
    @Override public int     executeUpdate(String sql, int[] columnIndexes) throws SQLException { return executeUpdate(sql); }
    @Override public int     executeUpdate(String sql, String[] columnNames) throws SQLException { return executeUpdate(sql); }
    @Override public boolean execute(String sql, int autoGeneratedKeys) throws SQLException { return execute(sql); }
    @Override public boolean execute(String sql, int[] columnIndexes) throws SQLException { return execute(sql); }
    @Override public boolean execute(String sql, String[] columnNames) throws SQLException { return execute(sql); }

    private java.util.List<String> batchSqls;

    @Override public void addBatch(String sql) throws SQLException {
        checkOpen();
        if (batchSqls == null) batchSqls = new java.util.ArrayList<>();
        batchSqls.add(sql);
    }

    @Override public void clearBatch() throws SQLException {
        checkOpen();
        if (batchSqls != null) batchSqls.clear();
    }

    @Override public int[] executeBatch() throws SQLException {
        checkOpen();
        if (batchSqls == null || batchSqls.isEmpty()) return new int[0];
        try {
            int[] results = new int[batchSqls.size()];
            for (int i = 0; i < batchSqls.size(); i++) {
                try {
                    results[i] = executeUpdate(batchSqls.get(i));
                } catch (SQLException e) {
                    throw new java.sql.BatchUpdateException(
                            e.getMessage(), e.getSQLState(), e.getErrorCode(),
                            java.util.Arrays.copyOf(results, i + 1), e);
                }
            }
            return results;
        } finally {
            batchSqls.clear();  // JDBC spec: always clear batch after executeBatch
        }
    }

    @Override public void    cancel() throws SQLException {}
    @Override public void    clearWarnings() throws SQLException {}
    @Override public SQLWarning getWarnings() throws SQLException { return null; }
    @Override public void    setCursorName(String name) throws SQLException {}
    @Override public void    setEscapeProcessing(boolean enable) throws SQLException {}
    @Override public boolean isPoolable() throws SQLException { return false; }
    @Override public void    setPoolable(boolean poolable) throws SQLException {}
    @Override public void    closeOnCompletion() throws SQLException {}
    @Override public boolean isCloseOnCompletion() throws SQLException { return false; }
    @Override public Connection getConnection() throws SQLException { return conn; }
    @Override public boolean isClosed() { return closed; }

    @Override public void close() throws SQLException {
        closed = true;
        if (currentRS != null) { currentRS.close(); currentRS = null; }
    }

    protected void checkOpen() throws SQLException {
        if (closed) throw new SQLException("Statement is closed");
    }

    @Override public <T> T unwrap(Class<T> iface) throws SQLException {
        if (iface.isInstance(this)) return iface.cast(this);
        throw new SQLException("Not a wrapper for " + iface);
    }
    @Override public boolean isWrapperFor(Class<?> iface) { return iface.isInstance(this); }
}
