package org.pgjava.catalog;

/** Whether a column is generated. */
public enum GeneratedKind {
    NONE,        // ordinary column
    ALWAYS,      // GENERATED ALWAYS AS (expr) STORED
    BY_DEFAULT   // GENERATED BY DEFAULT AS IDENTITY
}
